// Supabase configuration info
export const projectId = 'lwnqqjqaiauiqyxebehd';
export const publicAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bnFxanFhaWF1aXF5eGViZWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNjY0NzYsImV4cCI6MjA5MTk0MjQ3Nn0.g6wrTI53TTKnT5OMX41cnv1S4fMsq_6WqkBUz9INH3A';
